# Generated by Django 4.2.2 on 2023-07-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guru", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_records",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guru.pricerecord",
                    ),
                ),
            ],
        ),
    ]
