# Generated by Django 4.2.2 on 2023-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guru", "0002_stockstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockstats",
            name="stock",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
