# Generated by Django 4.2.2 on 2023-07-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guru", "0003_stockstats_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockstats",
            name="price_records",
        ),
    ]
