# Generated by Django 4.2.2 on 2023-07-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guru", "0004_remove_stockstats_price_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockstats",
            name="average_price",
        ),
        migrations.AddField(
            model_name="stockstats",
            name="most_recent_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
