# Generated by Django 4.2.2 on 2023-07-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guru", "0005_remove_stockstats_average_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockstats",
            name="price_difference_30days",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockstats",
            name="stock",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
