# Generated by Django 4.2.2 on 2023-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guru", "0006_stockstats_price_difference_30days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockstats",
            name="price_difference_1year",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockstats",
            name="price_difference_6months",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockstats",
            name="price_difference_30days",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
